name: workflow-01 example

on:
  push:
    branches:
      - main
      - "deploy-test"
  
  workflow_dispatch:


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - run: echo "The deploy was successful."
